# Generated by Django 5.2.11 on 2026-02-12 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_routehistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aqihistory',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aqihistory',
            name='lon',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
